language: python
python:
  - "2.7"
# command to install dependencies
install: "pip install --allow-all-external --allow-unverified ."
# command to run tests
script: python adlibre/Adlibre-DMS/adlibre_dms/manage.py test
