language: python

python:
  - "2.7"

services:
 - couchdb

# command to install dependencies
install: "pip install ."

before_script:
 - cp -rf fixtures ~/virtualenv/python2.7/lib/python2.7/site-packages/fixtures
 - mkdir ~/virtualenv/python2.7/lib/python2.7/site-packages/db
 - mkdir ~/virtualenv/python2.7/lib/python2.7/site-packages/log
 - python adlibre_dms/manage.py syncdb --noinput --all
 - python adlibre_dms/manage.py migrate core --fake
 - python adlibre_dms/manage.py migrate core --fake
 - python adlibre_dms/manage.py migrate dms_plugins --fake
 - python adlibre_dms/manage.py loaddata ~/virtualenv/python2.7/lib/site-packages/fixtures/initial_datas.json
 - python adlibre_dms/manage.py loaddata ~/virtualenv/python2.7/lib/site-packages/fixtures/core.json
 - python adlibre_dms/manage.py loaddata ~/virtualenv/python2.7/lib/site-packages/fixtures/djangoplugins.json
 - python adlibre_dms/manage.py loaddata ~/virtualenv/python2.7/lib/site-packages/fixtures/dms_plugins.json

# command to run tests
script: python adlibre_dms/manage.py test
